# Site settings
title: Ben Unsworth
email: ben.unsworth1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog and a place to keep links to things I am working on.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: benunsworth
github_username:  benunsworth
excerpt_separator: :<!--excerpt--> #insert this into posts to mark where the excerpts end

# Build settings
markdown: kramdown
