# Setup
title:               Ben Unsworth
tagline:             'Things I email myself'
description:         'A personal blog by Ben Unsworth'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ben Unnsworth
  url:               https://bsky.app/profile/benunsworth.co.uk
  email:             ben.unsworth1+blog@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #G-0J73RYL13Y
